project:
  type: default

format:
  revealjs:
    theme: default
    slide-level: 3
    slide-number: true
    transition: slide
    toc: true
    toc-depth: 1
    chalkboard: true
    scrollable: false
    smaller: false
    preview-links: auto
    css: custom.css
    mermaid:
      theme: neutral
